name: TestBuild

on: [push, pull_request]

jobs:
  windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v2.9.0
        with:
          version: '5.15.2'
      - name: Add msbuild to PATH
        uses: seanmiddleditch/gha-setup-vsdevenv@master
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run QMake
        run: qmake MApp.pro
      - name: Build
        run: |
          nmake
  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2-beta
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          modules: webenginewidgets
          version: '5.15.2'
      - name: Run QMake
        run: qmake MApp.pro
      - name: Build
        run: make
  mac:
    name: Mac
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2-beta
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          modules: webenginewidgets
          version: '5.15.2'
      - name: Run QMake
        run: qmake MApp.pro
      - name: Build
        run: make
